### ISSUE TITLE
[DataCap Application] <HenanZhongan> - <NREL Wind Integration National Dataset>

### ISSUE THREAD

**Issue by huaianle** [FIL-VSTAR/v5-notary#5]
### Data Owner Name

National Renewable Energy Laboratory

### Data Owner Country/Region

United States

### Data Owner Industry

Professional Services (Legal, Consulting, Advising)

### Website

https://hnzajpedu.com/#/

### Social Media Handle

公众号：河南中安教育

### Social Media Type

WeChat

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

1.1 PiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f1bpdlkaowo7f22rabi7gqtzhpohoub4i6ul7cl6q

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Henan Zhongan Jianpei Education Technology Co., Ltd. ("Henan Zhongan" for short) is an Internet education service organization focusing on vocational qualification certificate examination training and corporate talent training in the field of vocational education. The company settled in Zhengzhou through investment promotion and has now become the focus of investment promotion in the Seventh District of Zhengzhou No. 2 Middle School Enterprise and a key contract signing project for the "Three Batches" activities in Henan Province. It has a project license.
The company actively responds to the country's call for "Opinions on Promoting the High-Quality Development of Modern Education" and uses high-quality teachers, in-depth and pragmatic teaching styles and flexible and diverse vocational teaching methods to delve into the field of vocational education, pursue a professional development path, and integrate On the basis of high-quality resources such as professional colleges, industry mentors, and construction companies, we are based on the Internet education platform and continuously optimize the quality of products and services.
At present, Henan Zhongan relies on its advantages in teachers, products, and services to provide high-quality products and services for hundreds of millions of dollars across the country. It has developed into a comprehensive vocational education brand that provides policy research, application consultation, education and training and other services, creating a Realize career dreams and help corporate personnel improve their professional qualities.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Released to the public as part of the Department of Energy's Open Energy Data Initiative, the Wind Integration National Dataset (WIND) is an update and expansion of the Eastern Wind Integration Data Set and Western Wind Integration Data Set. It supports the next generation of wind integration studies.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We will download the 'NREL Wind Integration National Dataset' , and then use lotus or boost calculate to be file of car.
```

### Please share a sample of the data

```text
s3://nrel-pds-wtk/ 1.1PiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1.f01928097 Hong Kong
2.f02238701 US
3.f02132642 Singapore
4.f02826888 Toronto
5.f02836485 China
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by DDUPA** [comment]
Hello, @huaianle 

1. How did you manage to locate me to request for DC ?
2. How long have you been involved with the Filecoin Network ?
3. Please send an email to SnakePyQC@126.com using your company email.

**Comment by huaianle** [comment]
Hi , I find your allocator in https://github.com/filecoin-project/Allocator-Registry/tree/main/Allocators.My Slack name is CSKey.You can connect me with Slack. 
We join Filecoin for two years,and very interesting in Filecoin.
I will send you email for a moment.

**Comment by huaianle** [comment]
Hi we have sent the email with our offical email.
<img width="668" alt="图片" src="https://github.com/FIL-VSTAR/v5-notary/assets/169422968/1725e4c5-52a5-47f0-aeee-e117d3680c86">
