### ISSUE TITLE
[DataCap Application] Commoncrawl

### ISSUE THREAD

**Issue by techgood123** [FIL-VSTAR/v5-notary#7]
### Data Owner Name

Commoncrawl

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://commoncrawl.org/

### Social Media Handle

https://commoncrawl.org/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

512TiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1w2e4dn3kjcidr5bm6ifao243cqjhjbzlktago3y

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
TechToolbox is a technology services company that specializes in providing comprehensive solutions to our clients. We have a deep understanding of FILECOIN and excel at utilizing various tools to meet our clients' needs.

Our team consists of technical experts with extensive experience in the field. We recognize the significance of technology in modern business and are committed to delivering innovative and efficient solutions to our clients.

In the realm of FILECOIN, we are expert partners. We comprehend the working principles, potential, and application scenarios of FILECOIN, and we possess the expertise to optimize your FILECOIN experience using a wide range of tools and technologies.

Our services encompass a broad range of areas, including technology consulting, system integration, software development, and data analysis. Whether you are a startup or a well-established enterprise, we can provide customized solutions tailored to your specific requirements.

We prioritize our clients' success and work closely with them to ensure that our solutions help them achieve their business objectives. We are not just technology providers; we are collaborative partners dedicated to delivering excellence in technical services.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Common Crawl maintains a free, open repository of web crawl data that can be used by anyone.
Primary training corpus in every LLM.82% of raw tokens used to train GPT-3.Free and open corpus since 2007.Cited in over 8000 research papers.3–5 billion new pages added each month.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I am data preparer, TechToolbox have technical team that specializes in providing Car data packaging services to our clients, which include: 1. technical expertise: our team is skilled in using advanced tools such as go-graphsplit, singularity, etc. to ensure efficient and accurate data packaging. 2. Data Processing Flow: We use self-developed programs to cut, package, and compress the data provided by our clients into 28-32GB zip files to meet the storage requirements of the Filecoin network. Through these services, we are able to effectively help our clients process and prepare data for storage and use on the Filecoin network.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
This data set has 15P. Currently, no one has completely stored the data on the Filecoin network.
```

### Please share a sample of the data

```text
https://commoncrawl.org/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

IPFS, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02941878 、f02941888 、f02941882 、f02941891 、f02941885 、f02941886、f02945259 、f02945258
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by techgood123** [comment]
We have rich experience, https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/2184 was applied by our colleagues, we applied https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues  and https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/issues/5 and https://github.com/Blockchain-World-News/FIL-DC-Allocator/issues/5, we are ready and look forward to seeing your approval

**Comment by DDUPA** [comment]
Hi,  @techgood123  I have a few questions:

- Please tell me the geographical location of the SPs you cooperate with?
- How much data have you prepared? Can you show the details?
- Do these SPs support data retrieval?

**Comment by techgood123** [comment]
f03071472- HK
f03028318- HK
f02830476- Guangdong
f03028326 -Guangdong
f03028321- HK
f03028325- HK
f03028310- HK
f03028315- HK

**Comment by techgood123** [comment]
We have prepared 300TiB of data and are still preparing it.
<img width="904" alt="289248063-43acc7be-4f42-44ca-adb3-3bc9192b3fae" src="https://github.com/FIL-VSTAR/v5-notary/assets/127367768/2daae6f8-ca3c-417e-8f42-756db9faeae7">

**Comment by techgood123** [comment]
SP supports retrieval, thank you

**Comment by DDUPA** [comment]
checker:manualTrigger

**Comment by DDUPA** [comment]
checker:manualTrigger

**Comment by yse88483** [comment]
checker:manualTrigger

**Comment by gimims** [comment]
checker:manualTrigger
